# Generated by Django 5.2.4 on 2025-10-27 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_package_detail',
            name='status',
            field=models.CharField(choices=[('waiting comfirmation', 'waiting comfirmation'), ('pending', 'pending'), ('delayed', 'delayed'), ('active', 'active')], default=3, max_length=21),
        ),
        migrations.CreateModel(
            name='TrackingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('package_received', 'Package Received'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('waiting_confirmation', 'Waiting Confirmation')], default='order_confirmed', max_length=20)),
                ('message', models.TextField(default='Status update')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='tracker.user_package_detail')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
